services:
  - type: pserv
    name: tecopos-kafka
    env: docker
    plan: starter
    dockerContext: .
    dockerfilePath: ./render/kafka.Dockerfile
    envVars:
      - key: KAFKA_NODE_ID
        value: '1'
      - key: KAFKA_PROCESS_ROLES
        value: 'broker,controller'
      - key: KAFKA_LISTENERS
        value: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      - key: KAFKA_ADVERTISED_LISTENERS
        value: 'PLAINTEXT://tecopos-kafka:9092'
      - key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      - key: KAFKA_INTER_BROKER_LISTENER_NAME
        value: 'PLAINTEXT'
      - key: KAFKA_CONTROLLER_LISTENER_NAMES
        value: 'CONTROLLER'
      - key: KAFKA_CONTROLLER_QUORUM_VOTERS
        value: '1@tecopos-kafka:9093'
      - key: CLUSTER_ID
        value: '4L6g3nShT-eMCtK--X86sw'
      - key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: '1'
      - key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
        value: '1'
      - key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
        value: '1'
      - key: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
        value: '0'

  - type: pserv
    name: tecopos-sso
    env: docker
    plan: starter
    dockerContext: .
    dockerfilePath: ./render/sso.Dockerfile
    envVars:
      - key: KAFKA_BROKERS
        value: 'tecopos-kafka:9092'
      - key: DATABASE_URL
        sync: false

  - type: pserv
    name: tecopos-banking
    env: docker
    plan: starter
    dockerContext: .
    dockerfilePath: ./render/banking.Dockerfile
    envVars:
      - key: KAFKA_BROKERS
        value: 'tecopos-kafka:9092'
      - key: BANKING_API_BASE_URL
        sync: false

  - type: web
    name: tecopos-gateway
    env: docker
    plan: starter
    dockerContext: .
    dockerfilePath: ./render/gateway.Dockerfile
    envVars:
      - key: KAFKA_BROKERS
        value: 'tecopos-kafka:9092'
